travis:
  secure:
    BINSTAR_TOKEN: DLaGO2QI76v2aj2QqqxCgYMc/UgA+IESorpv6ldwYP8l6rbFc9IzJOkO5GMsKSa6O4atBEsvd7M6m5s+G8Neoc4KNsLwau08+hFMte5h05gBqT9yqWPtA9B5ZFY3yOf96xcmvvzP+u3D6Aswe4PwPXUMsgvkiJRHseSUNHI9zqbWQAMESLo832D1dv59Of1SHsTjTU9Z5Q+vdqH0Xg/vTcNv+c42MVDR9cUyrGdvB1mkL3hwyfj+eHA+ZW+zPBJPraN5i8QXtobaBIVjaViR82EpOONFpG2BfT5XZSaI6X3PUhvqgPNQgWJY/ektCzGE3TbN29n9Ht88CzBTmSZ+eF7d+pmRiZDuvPAYTUhYjBIhR4F2uuqyOgPeXTtCaG1a420xkoQPV46/GmJl4I5wSkdfxl/ijYvlpFXNKQMGqvxje/KIRt2u7yLteVVdgCj6bYSGoUkiiPJYVm4N55o8A8W1bgQw8CaMTNs9c1Wz1ecAj+v73m0GvTUHLAsKoca9X/1wtVZ5Hrp/+l9Sarsv1yYlsOn+IQZZivGNjOU0uBjf+nU8rpNB1WUpsspseOZsIV4bubWoFzIB+xGax5syyIk2KAhOHC3YUHOkujuzFv7b385KjFUqpxLLkgIShA+SJA1qdxDTN7QuDyfRBuxzbD4rHcRAa4cm1VuDQM2JdOA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
