travis:
  secure:
    BINSTAR_TOKEN: TR6EI90XB/LTn7c9CxjNdXk6nLIxgGYNO7nvIT0NgDpaJX2scNXNKzNShssY7U6a2UkNFUhEF9O3soZFIP+EHwdithwKMcUeQLrEgJHzOOhgXN6c1lU0dUHina3xAwW9+En5WNQCrX1EUtQAcjT022J92he+r5cTKREtHFkhpevRTvEmQ+yzFJeUBXWX3Eek5DqVMyALnL2e9d1cl/5S5P5OTW4pJNgK50srlHy9tU/rV9FRMMDvks1uLIvyjmZTo79xCErIg5EyMmnZ3mvXHxWzYyNXiRa5+nCiINLEF7BeLKPddvua1EET09YhxLhSTrU400LeCjc8CZAYy3zxhtU41WETnHZGIAHbLbNi9dtnnfivwTSOHiTeaiA61MUwu3WrTpOSspQunPc6tTLwNBsCTvZlg/NpFk/fui5pP7Ha8rMq1hKYbSJ6KI7ftLN95iHhNK4Ivz+l61c45aSxW1y2LL8kPrICk4Rqx9z+PkNSskF/WXVD0Y3NUmmOXEkL0G/bz413PPKQ9D6CpsvthYfX4kNKUxvbYvxytKSTN9Ev7vpaFXAhkKvaoFqChgEHjbME1KtZfkRq3ss5T95p2924IxGWv933A/+AxIir5/xUxsFOXx816+eeaPrFpmZmzlPVOQ8mbetSEXf7p5RLPJTZCixyKkb3sySdxNpJAMU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
